"""add_user_asset_junction_table

Revision ID: 12abc5ce7d5b
Revises: 1d65f85b8afe
Create Date: 2026-04-16 09:01:31.596846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12abc5ce7d5b'
down_revision: Union[str, Sequence[str], None] = '1d65f85b8afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_user_asset')
    )
    op.create_index(op.f('ix_user_assets_asset_id'), 'user_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_user_assets_user_id'), 'user_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_assets_user_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_asset_id'), table_name='user_assets')
    op.drop_table('user_assets')
    # ### end Alembic commands ###
