"""created_at column added to alert rule model

Revision ID: 1d65f85b8afe
Revises: 05b80b2fcdc7
Create Date: 2026-04-08 05:56:16.304599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d65f85b8afe'
down_revision: Union[str, Sequence[str], None] = '05b80b2fcdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'created_at')
    # ### end Alembic commands ###
