"""curretnt_price field added to Asset model

Revision ID: 6252244c5a21
Revises: 690d21ab0c10
Create Date: 2026-03-27 18:03:37.754419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6252244c5a21'
down_revision: Union[str, Sequence[str], None] = '690d21ab0c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'current_price')
    # ### end Alembic commands ###
