"""alert_id field changed to uuid for alert model

Revision ID: 7d9e0b1b1d9c
Revises: d8cb2467a423
Create Date: 2026-04-05 12:39:43.503676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9e0b1b1d9c'
down_revision: Union[str, Sequence[str], None] = 'd8cb2467a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('last_triggered_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('assets_coingecko_id_key'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_coingecko_id'), 'assets', ['coingecko_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_coingecko_id'), table_name='assets')
    op.create_unique_constraint(op.f('assets_coingecko_id_key'), 'assets', ['coingecko_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('alert_rules', 'last_triggered_at')
    # ### end Alembic commands ###
