"""symbol and name field updated for assets model

Revision ID: af1df808466e
Revises: cafb8b6e49c7
Create Date: 2026-03-24 08:56:36.719889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1df808466e'
down_revision: Union[str, Sequence[str], None] = 'cafb8b6e49c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_symbol_key'), 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=True)
    op.create_unique_constraint(op.f('assets_symbol_key'), 'assets', ['symbol'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
