"""Intial userprofile model added

Revision ID: c06fd54ab25a
Revises: 12abc5ce7d5b
Create Date: 2026-04-17 12:10:32.475733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06fd54ab25a'
down_revision: Union[str, Sequence[str], None] = '12abc5ce7d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('preferred_currency', sa.String(length=10), nullable=False),
    sa.Column('risk_tolerance', sa.String(), nullable=False),
    sa.Column('trading_experience', sa.String(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('price_alert_notifications', sa.Boolean(), nullable=False),
    sa.Column('market_update_notifications', sa.Boolean(), nullable=False),
    sa.Column('newsletter_subscription', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('default_chart_timeframe', sa.String(length=20), nullable=False),
    sa.Column('show_portfolio_on_dashboard', sa.Boolean(), nullable=False),
    sa.Column('default_alert_condition', sa.String(), nullable=False),
    sa.Column('alert_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('max_active_alerts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
