"""AuthAccount model added

Revision ID: c58fe589cf71
Revises: b2a41f613fc4
Create Date: 2026-03-23 19:39:49.368293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58fe589cf71'
down_revision: Union[str, Sequence[str], None] = 'b2a41f613fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=65), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_account_id')
    )
    op.add_column('alert_rules', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('alert_rules', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_alert_rules_is_active'), 'alert_rules', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'alert_rules', ['user_id', 'asset_id', 'target_price', 'condition_type'])
    op.drop_constraint(op.f('alert_rules_user_id_fkey'), 'alert_rules', type_='foreignkey')
    op.create_foreign_key(None, 'alert_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('price_snapshots_asset_id_fkey'), 'price_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('price_snapshots_asset_id_fkey'), 'price_snapshots', 'assets', ['asset_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'alert_rules', type_='foreignkey')
    op.create_foreign_key(op.f('alert_rules_user_id_fkey'), 'alert_rules', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'alert_rules', type_='unique')
    op.drop_index(op.f('ix_alert_rules_is_active'), table_name='alert_rules')
    op.drop_column('alert_rules', 'updated_at')
    op.drop_column('alert_rules', 'is_active')
    op.drop_table('auth_accounts')
    # ### end Alembic commands ###
